"""Added Comentario model

Revision ID: 3a80616287be
Revises: f22d6a88952c
Create Date: 2026-03-08 16:30:22.056760

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3a80616287be'
down_revision = 'f22d6a88952c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('comentarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('conteudo', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('aprovado', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('pratica_id', sa.Integer(), nullable=True),
    sa.Column('artigo_id', sa.Integer(), nullable=True),
    sa.Column('pesquisa_id', sa.Integer(), nullable=True),
    sa.Column('noticia_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['artigo_id'], ['artigos.id'], name=op.f('fk_comentarios_artigo_id_artigos')),
    sa.ForeignKeyConstraint(['noticia_id'], ['noticias.id'], name=op.f('fk_comentarios_noticia_id_noticias')),
    sa.ForeignKeyConstraint(['pesquisa_id'], ['pesquisas.id'], name=op.f('fk_comentarios_pesquisa_id_pesquisas')),
    sa.ForeignKeyConstraint(['pratica_id'], ['praticas.id'], name=op.f('fk_comentarios_pratica_id_praticas')),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_comentarios_user_id_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_comentarios'))
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('comentarios')
    # ### end Alembic commands ###
