"""Added user role

Revision ID: 994e9e00af64
Revises: 2bab07f2792e
Create Date: 2026-03-08 13:55:43.945408

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '994e9e00af64'
down_revision = '2bab07f2792e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(length=20), nullable=False, server_default='user'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('role')

    # ### end Alembic commands ###
