"""Added Artigo Pesquisa Noticia and updated fields v2

Revision ID: f22d6a88952c
Revises: 994e9e00af64
Create Date: 2026-03-08 16:10:44.725767

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f22d6a88952c'
down_revision = '994e9e00af64'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('praticas', schema=None) as batch_op:
        batch_op.add_column(sa.Column('author_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(batch_op.f('fk_praticas_author_id_users'), 'users', ['author_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('praticas', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_praticas_author_id_users'), type_='foreignkey')
        batch_op.drop_column('author_id')

    # ### end Alembic commands ###
